name: Python linting

on: [push, pull_request, workflow_dispatch]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: |
          setup.cfg
          requirements/*.txt

    - name: Install dependencies
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        pip install -r requirements/linux.txt -r requirements/linux-dev.txt -e .

    - name: Check for formatting/linting errors
      run: |
        isort --check-only .
        black --check .
        flake8 --count --statistics .
