name: Python linting

on: [push, pull_request, workflow_dispatch]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m ensurepip --upgrade
        pip install black flake8 isort>=5.0
    - name: Check for formatting/linting errors
      run: |
        isort --check-only .
        black --check .
        flake8 --count --statistics --statistics .
